./testbench/tb_top.v
./rtl/sdr_parameters.vh
./testbench/sdram_model.v
./rtl/top.v
./rtl/rst_synchronizer.v
./rtl/cmd_decode.v
./rtl/fifo_async.v
./rtl/fifo_async_btog_cvtr.v
./rtl/uart_rx.v
./rtl/uart_tx.v
./rtl/sdram_top.v
./rtl/sdram_write.v
./rtl/sdram_read.v
./rtl/sdram_init.v
./rtl/sdram_aref.v
