./testbench/tb_top.v
./rtl/top.v
./rtl/alu.v
./rtl/alu_1_bit.v
./rtl/alu_ctrl.v
./rtl/comp_ab.v
./rtl/comp_wab.v
./rtl/data_mem.v
./rtl/fa.v
./rtl/forward.v
./rtl/imme_extend.v
./rtl/instruction_mem.v
./rtl/jump_target.v
./rtl/main_ctrl.v
./rtl/mult_array.v
./rtl/pc_add4.v
./rtl/pc_add_target.v
./rtl/pc_ctr.v
./rtl/pipreg_exmem.v
./rtl/pipreg_idex.v
./rtl/pipreg_ifid.v
./rtl/pipreg_memwb.v
./rtl/rfile.v
./rtl/stall.v
